ECHO Welcome to optimization of H1with MO
CALL python hydra_app.py general=H1_MO_conf_1_0.1 optimization=H1_MO_conf_1_0.1
ECHO Finished optimization of conf_1_0.1
CALL python hydra_app.py general=H1_MO_conf_1_0.25 optimization=H1_MO_conf_1_0.25
ECHO Finished optimization of conf_1_0.25
CALL python hydra_app.py general=H1_MO_conf_1_0.5 optimization=H1_MO_conf_1_0.5
ECHO Finished optimization of conf_1_0.5
CALL python hydra_app.py general=H1_MO_conf_1_1 optimization=H1_MO_conf_1_1
ECHO Finished optimization of conf_1_1
CALL python hydra_app.py general=H1_MO_conf_2_0.1 optimization=H1_MO_conf_2_0.1
ECHO Finished optimization of conf_2_0.1
CALL python hydra_app.py general=H1_MO_conf_2_0.25 optimization=H1_MO_conf_2_0.25
ECHO Finished optimization of conf_2_0.25
CALL python hydra_app.py general=H1_MO_conf_2_0.5 optimization=H1_MO_conf_2_0.5
ECHO Finished optimization of conf_2_0.5
CALL python hydra_app.py general=H1_MO_conf_2_1 optimization=H1_MO_conf_2_1
ECHO Finished optimization of conf_2_1
CALL python hydra_app.py general=H1_MO_conf_3_0.1 optimization=H1_MO_conf_3_0.1
ECHO Finished optimization of conf_3_0.1
CALL python hydra_app.py general=H1_MO_conf_3_0.25 optimization=H1_MO_conf_3_0.25
ECHO Finished optimization of conf_3_0.25
CALL python hydra_app.py general=H1_MO_conf_3_0.5 optimization=H1_MO_conf_3_0.5
ECHO Finished optimization of conf_3_0.5
CALL python hydra_app.py general=H1_MO_conf_3_1 optimization=H1_MO_conf_3_1
ECHO Finished optimization of conf_3_1
CALL python hydra_app.py general=H1_MO_conf_4_0.1 optimization=H1_MO_conf_4_0.1
ECHO Finished optimization of conf_4_0.1
CALL python hydra_app.py general=H1_MO_conf_4_0.25 optimization=H1_MO_conf_4_0.25
ECHO Finished optimization of conf_4_0.25
CALL python hydra_app.py general=H1_MO_conf_4_0.5 optimization=H1_MO_conf_4_0.5
ECHO Finished optimization of conf_4_0.5
CALL python hydra_app.py general=H1_MO_conf_4_1 optimization=H1_MO_conf_4_1
ECHO Finished optimization of conf_4_1
