site_name: prodsys Documentation
theme: 
  name: material
  features:
    - content.code.copy

plugins:
- search
- include_dir_to_nav
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: false
          filters:
            - "!^_[^_]"
            - "!^__[^_]"
        selection:
          filters:
            - "!model_computed_fields"
            - "!model_config"
            - "!model_fields"

nav:
- Home: index.md
- Tutorials: Tutorials
- Api Reference: API_reference

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences